---
- name: Deploy Calculator Container
  hosts: localhost

  tasks:

    - name: Pull latest Docker image
      community.docker.docker_image:
        name: 2001vivekjoshi/calculator-app
        tag: latest
        source: pull

    - name: Stop and remove existing container
      community.docker.docker_container:
        name: calculator-container
        state: absent


    - name: Run new container
      community.docker.docker_container:
        name: calculator-container
        image: 2001vivekjoshi/calculator-app:latest
        state: started
        recreate: true
        tty: true
        interactive: true
        restart_policy: always