---
- name: Deploy Calculator Application
  hosts: local
  become: yes

  tasks:

    - name: Pull latest Docker image
      command: docker pull 2001vivekjoshi/calculator-app:latest


    - name: Remove existing container if present
      command: docker rm -f calculator-container
      ignore_errors: yes

    - name: Run new container
      command: docker run -d --name calculator-container --restart always 2001vivekjoshi/calculator-app:latest